# For more information about the available options please visit: http://go/backstage (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/AnthroNet
    backstage.io/techdocs-ref: dir:.
  name: AnthroNet
  description: "AnthroNet: Conditional Generation of Humans via Anthropometrics"
  labels:
    costcenter: "5029"
  tags:
    - planned-public
spec:
  type: website
  lifecycle: production
  owner: unity-technologies/ai
