# name: Robotics <Repo> Tests
# agent:
#     type: Unity::VM
#     image: robotics/ci-ubuntu20:latest
#     flavor: i1.large
# variables:
#     PATH: /root/.local/bin:/home/bokken/bin:/home/bokken/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/home/bokken/.npm-global/bin
# commands:
#       # TODO
# triggers:
#     cancel_old_ci: true
#     expression: |
#         (pull_request.target eq "main"  AND
#         NOT pull_request.push.changes.all match ["**/*.md","**/*.jpg","**/*.jpeg","**/*.gif","**/*.pdf"]) OR
#         (push.branch eq "dev" AND
#         NOT push.changes.all match ["**/*.md","**/*.jpg","**/*.jpeg","**/*.gif","**/*.pdf"])
# artifacts:
#     logs:
#         paths:
#             - "test-results/**/*"
